# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-11 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wander', '0002_traveler_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.CharField(default='Waiting', max_length=12),
        ),
    ]
