# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-11 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wander', '0003_trip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wander.Guide'),
        ),
    ]
