# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-11 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wander', '0004_auto_20160911_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
