# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-11 08:56
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wander', '0005_traveler_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='interest',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='end_location',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_location',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
    ]
